CREATE FUNCTION FUNCIONFACTORIAL (@VALOR1 INTEGER)
RETURNS INT
AS
BEGIN
	DECLARE @NUMFACT INT;

	IF  (@VALOR1=1)  SET @NUMFACT=1;
	ELSE 

	SET @NUMFACT= @VALOR1*FUNCIONFACTORIAL (@VALOR1-1);
	 RETURN @NUMFACT;
END;

SELECT FUNCIONFACTORIAL(5) 